version: '3'
services:
 web:
#   restart: always
  environment:
   - CHOKIDAR_USEPOLLING=true
  stdin_open: true
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "3000:3000"
  volumes:
   - /app/node_modules
   - .:/app
#    - /c/Users/oppor/workspace/Docker/UI/frontend:/app
 tests:
  build:
   context: .
   dockerfile: Dockerfile.dev
  volumes:
   - /app/node_modules
   - .:/app
#    - /c/Users/oppor/workspace/Docker/UI/frontend:/app
  command: ["npm", "run", "test"]